"""Move ts defaults to server in users table

Revision ID: 3361888597f4
Revises: abd4943e2e7c
Create Date: 2022-03-08 06:25:27.495241

"""

# revision identifiers, used by Alembic.
revision = "3361888597f4"
down_revision = "abd4943e2e7c"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "created_at", server_default=sa.text("now() at time zone 'utc'")
    )
    op.alter_column(
        "users",
        "updated_at",
        server_default=sa.text("now() at time zone 'utc'"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.alter_column("users", "created_at", server_default=None)
    op.alter_column(
        "users",
        "updated_at",
        server_default=None,
    )
